name: Scheduled Merge Remote Action

# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
# Operator	Description	Example
# *	Any value	* * * * * runs every minute of every day.
# ,	Value list separator	2,10 4,5 * * * runs at minute 2 and 10 of the 4th and 5th hour of every day.
# -	Range of values	0 4-6 * * * runs at minute 0 of the 4th, 5th, and 6th hour.
# /	Step values	20/15 * * * * runs every 15 minutes starting from minute 20 through 59 (minutes 20, 35, and 50).

on: 
  push:
  schedule:
    - cron: '0 */3 * * *'
    # runs every 3 hours of everyday


# This is what will cancel the previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
        - name: Checkout
          uses: actions/checkout@v4.1.1
          with:
            ref: repacker             # set the branch to merge to
            fetch-depth: 0 
        - name: Merge Upstream
          run: | 
              git remote add -f upstream "https://github.com/vmangos/core.git"
              git remote -v
              git branch --all
              git config --global user.email "actions@github.com"
              git config --global user.name "Merge Upstream Action"
              git checkout repacker
              git merge upstream/development
              git push origin repacker
              
                  
